Repository WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner, pull requests merged in 2024-07, with the labels that each got.

#25 Signup page
  backend/src/resolvers/UserResolver.ts
  e2e-tests/src/home.spec.ts
  frontend/src/pages/signup.tsx
Labels: REVIEWED

#27 login page style
  backend/src/resolvers/UserResolver.ts
  frontend/src/pages/login.tsx
Labels: REQUESTED REVIEW

#29 added error handling style
  frontend/src/pages/signup.tsx
Labels: REVIEWED

#31 removed unused avatar functions and better error handling
  frontend/src/pages/signup.tsx
Labels: REVIEWED

#30 Layout
  frontend/package-lock.json
  frontend/package.json
  frontend/public/Gifty-logo-white.svg
  frontend/src/components/Footer.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/graphql/user/mutation/logout.gql
  frontend/src/pages/_app.tsx
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/index.tsx
  frontend/src/theme/components/Button.ts
  frontend/src/theme/components/MenuItem.ts
  frontend/src/theme/config.ts
Labels: REVIEWED

#32 fixed right password and passwordConfirmation counted as wrong
  frontend/src/pages/signup.tsx
Labels: REQUESTED REVIEW

#33 [FEAT] Us17#2 dashboard with group
  .env.production.example
  .gitignore
  backend/src/resetDb.ts
  backend/src/resolvers/GroupResolver.ts
  backend/src/resolvers/UserResolver.ts
  backend/src/types/ContextType.ts
  backend/src/types/NewGroupInputType.ts
  frontend/src/components/Navbar.tsx
  frontend/src/components/Test.tsx
  frontend/src/components/dashboard/DashboardWithGroup.tsx
  frontend/src/components/group/CreateGroupModal.tsx
  frontend/src/components/group/FormCreateGroup.tsx
  frontend/src/components/group/GroupList.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/graphql/group/mutation/CreateGroup.gql
  frontend/src/graphql/user/queries/GetProfile.gql
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/index.tsx
  frontend/src/theme/components/Button.ts
  frontend/src/theme/components/Form.ts
  frontend/src/theme/components/Input.ts
  frontend/src/theme/components/MenuItem.ts
  frontend/src/theme/config.ts
  frontend/tailwind.config.ts
Labels: REVIEWED, CORRECTED

#37 Us04 add members
  backend/src/config/schema.ts
  backend/src/entities/Group.ts
  backend/src/resetDb.ts
  backend/src/resolvers/GroupResolver.ts
  backend/src/resolvers/MemberResolver.ts
  backend/src/types/NewGroupInputType.ts
  backend/src/types/ObjectIdType.ts
  frontend/src/components/group/FormCreateGroup.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/graphql/group/mutation/CreateGroup.gql
  frontend/src/pages/dashboard.tsx
  frontend/src/theme/components/Button.ts
  frontend/src/theme/components/Input.ts
  frontend/src/theme/config.ts
Labels: REQUESTED REVIEW

#38 Profile page revamp
  frontend/src/components/Footer.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/pages/profile.tsx
  frontend/src/theme/components/Button.ts
  frontend/src/types/isDefined.ts
  frontend/src/types/isValidNotEmptyString.ts
Labels: REQUESTED REVIEW

#39 US04 add members with email
  backend/src/entities/Group.ts
  backend/src/resetDb.ts
  backend/src/resolvers/GroupResolver.ts
  backend/src/resolvers/UserResolver.ts
  backend/src/services/userService.ts
  backend/src/types/NewGroupInputType.ts
  frontend/src/components/Footer.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/dashboard/DashboardWithGroup.tsx
  frontend/src/components/dashboard/DashboardWithoutGroup.tsx
  frontend/src/components/group/CreateGroupModal.tsx
  frontend/src/components/group/FormCreateGroup.tsx
  frontend/src/components/group/GroupList.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/graphql/user/queries/GetProfile.gql
  frontend/src/pages/dashboard.tsx
  frontend/src/styles/globals.css
  frontend/src/theme/config.ts
Labels: CHANGES REQUESTED
