Repository WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner, pull requests merged in 2024-06, with the labels that each got.

#12 loginPage
  backend/src/resolvers/UserResolver.ts
  frontend/src/pages/login.tsx
  frontend/src/pages/signup.tsx
Labels: REVIEWED

#14 Test integration
  backend/__tests__/operations/addUser.ts
  backend/__tests__/operations/getUsers.ts
  backend/__tests__/usersResolver.test.ts
  backend/docker-compose.integration-tests.yml
  backend/jest.config.ts
  backend/jest.setup.ts
  backend/package-lock.json
  backend/package.json
  backend/src/config/db.ts
  backend/src/env.ts
  backend/src/resolvers/UserResolver.ts
  frontend/src/graphql/generated/schema.ts
Labels: REQUESTED REVIEW

#13 add integration tests front and back
  .github/workflows/integration-tests.yml
  .github/workflows/test-front.yml
  backend/.env.example
  backend/.env.exemple
  backend/__tests__/operations/addUser.ts
  backend/__tests__/usersResolver.test.ts
  backend/jest.setup.ts
  backend/src/resolvers/UserResolver.ts
  frontend/.env.example
Labels: REQUESTED REVIEW

#16 Homepage mobile
  frontend/package-lock.json
  frontend/package.json
  frontend/public/Gifty-logo.svg
  frontend/src/pages/index.tsx
Labels: REVIEWED

#17 test e2e ok
  backend/Dockerfile
  e2e-tests/.env.example
  e2e-tests/.gitignore
  e2e-tests/docker-compose.e2e-tests.yml
  e2e-tests/package-lock.json
  e2e-tests/package.json
  e2e-tests/playwright.config.ts
  e2e-tests/src/dbHelpers.ts
  e2e-tests/src/home.spec.ts
  e2e-tests/tsconfig.json
  frontend/Dockerfile
  frontend/src/pages/signup.tsx
Labels: MERGED

#18 Authchecker
  backend/__tests__/usersResolver.test.ts
  backend/src/config/auth.ts
  backend/src/config/schema.ts
  backend/src/entities/User.ts
  backend/src/resetdb.ts
  backend/src/resolvers/UserResolver.ts
  backend/src/types/NewUserInputType.ts
  frontend/src/graphql/generated/schema.ts
  frontend/src/graphql/user/queries/GetProfile.gql
  frontend/src/pages/index.tsx
Labels: REQUESTED REVIEW

#19 Variables initialization
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/signup.tsx
  frontend/src/theme/config.ts
Labels: REVIEWED

#22 fixed case sensitive file name
  backend/src/resetDb.ts
Labels: REQUESTED REVIEW

#21 build back and front in ci
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
  .github/workflows/deploy-production.yml
  .github/workflows/e2e-tests.yml
  backend/Dockerfile.production
  backend/__tests__/usersResolver.test.ts
  backend/src/types/NewUserInputType.ts
  frontend/package-lock.json
  frontend/src/theme/config.ts
Labels: REVIEWED
