Repository WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner, pull requests merged in 2024-10, with the labels that each got.

#50 added validation data, updating and deleting a group
  backend/.env.example
  backend/src/config/mailer.ts
  backend/src/resolvers/GroupResolver.ts
  backend/src/resolvers/MemberResolver.ts
  frontend/src/components/ConfirmModal.tsx
  frontend/src/components/Error.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/Loader.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/group/AddMembersModal.tsx
  frontend/src/components/group/CreateGroupModal.tsx
  frontend/src/components/group/FormAddMembers.tsx
  frontend/src/components/group/FormCreateGroup.tsx
  frontend/src/contexts/ErrorContext.tsx
  frontend/src/contexts/GroupContext.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/graphql/group/mutation/DeleteGroup.gql
  frontend/src/graphql/group/mutation/UpdateGroupName.gql
  frontend/src/hooks/useFormValidation.tsx
  frontend/src/locales/en/translation.json
  frontend/src/locales/fr/translation.json
  frontend/src/pages/_app.tsx
  frontend/src/pages/completeProfile.tsx
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/group/[id].tsx
  frontend/src/styles/globals.css
  frontend/src/theme/components/Button.ts
  frontend/src/theme/components/Input.ts
  frontend/src/theme/components/Toast.ts
  frontend/src/theme/config.ts
  frontend/src/types/ErrorContextType.ts
  frontend/src/types/GroupContextProps.ts
Labels: REVIEWED

#52 Channels front page update
  backend/src/resolvers/MemberResolver.ts
  frontend/src/components/group/AddMembersModal.tsx
  frontend/src/pages/group/[id].tsx
Labels: REVIEWED

#51 changed inputs style and few more styling adjustment for login and si…
  e2e-tests/src/home.spec.ts
  frontend/src/pages/login.tsx
  frontend/src/pages/profile.tsx
  frontend/src/pages/signup.tsx
  frontend/src/theme/config.ts
Labels: REQUESTED REVIEW

#55 User channel relation
  backend/src/entities/Channel.ts
  backend/src/entities/User.ts
  backend/src/resolvers/ChannelResolver.ts
  backend/src/resolvers/GroupResolver.ts
  frontend/src/components/group/FormCreateGroup.tsx
  frontend/src/graphql/channel/mutations/createChannels.gql
  frontend/src/graphql/channel/queries/getChannels.gql
  frontend/src/graphql/generated/schema.ts
  frontend/src/pages/group/[id].tsx
Labels: MERGED

#56 Fix add members to group
  backend/src/resolvers/GroupResolver.ts
  backend/src/services/emailService.ts
  frontend/src/components/SearchBar.tsx
  frontend/src/components/dashboard/DashboardWithGroup.tsx
  frontend/src/components/group/FormAddMembers.tsx
  frontend/src/components/group/FormCreateGroup.tsx
  frontend/src/components/group/GroupList.tsx
  frontend/src/locales/en/translation.json
  frontend/src/locales/fr/translation.json
  frontend/src/pages/completeProfile.tsx
  frontend/src/pages/group/[id].tsx
Labels: REQUESTED REVIEW

#61 Fix vps
  .env.production.example
  README.md
  frontend/public/Gifty-logo-light.svg
  frontend/src/contexts/ErrorContext.tsx
  frontend/src/locales/en/translation.json
  frontend/src/locales/fr/translation.json
  frontend/src/pages/_app.tsx
Labels: MERGED

#68 Fix navbar
  backend/.env.example
  backend/src/entities/Channel.ts
  e2e-tests/src/home.spec.ts
  frontend/src/components/Layout.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/group/FormCreateGroup.tsx
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/index.tsx
Labels: REVIEWED

#70 Delete user account
  backend/src/resolvers/UserResolver.ts
  frontend/src/components/Layout.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/dashboard/DashboardWithGroup.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/graphql/user/mutation/Delete.gql
  frontend/src/hooks/useAuthRedirect.tsx
  frontend/src/locales/en/translation.json
  frontend/src/locales/fr/translation.json
  frontend/src/pages/group/[id].tsx
  frontend/src/pages/group/[id]/channel/[memberId].tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/profile.tsx
  frontend/src/pages/signup.tsx
Labels: REQUESTED REVIEW

#73 added subscription loction to nginx
  gateway/nginx.conf
Labels: REVIEWED

#71 Update query channel
  backend/src/resolvers/ChannelResolver.ts
  frontend/src/components/group/AddMembersModal.tsx
  frontend/src/components/group/FormAddMembers.tsx
  frontend/src/graphql/generated/schema.ts
  frontend/src/pages/group/[id].tsx
  frontend/src/pages/index.tsx
Labels: REVIEWED

#72 update to reset db file
  backend/src/resetDb.ts
Labels: REQUESTED REVIEW
